books = [
    {
        "id": 1,
        "title": "The Pragmatic Programmer",
        "author": "Andrew Hunt, David Thomas",
        "publisher": "Addison-Wesley",
        "published_date": "1999-10-20",
        "page_count": 352,
        "language": "English",
    },
    {
        "id": 2,
        "title": "Clean Code",
        "author": "Robert C. Martin",
        "publisher": "Prentice Hall",
        "published_date": "2008-08-01",
        "page_count": 464,
        "language": "English",
    },
    {
        "id": 3,
        "title": "Design Patterns",
        "author": "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
        "publisher": "Addison-Wesley",
        "published_date": "1994-10-21",
        "page_count": 395,
        "language": "English",
    },
    {
        "id": 4,
        "title": "Introduction to the Theory of Computation",
        "author": "Michael Sipser",
        "publisher": "Cengage",
        "published_date": "1996-01-01",
        "page_count": 480,
        "language": "English",
    },
    {
        "id": 5,
        "title": "The Art of Computer Programming",
        "author": "Donald Knuth",
        "publisher": "Addison-Wesley",
        "published_date": "1968-01-01",
        "page_count": 672,
        "language": "English",
    },
    {
        "id": 6,
        "title": "Structure and Interpretation of Computer Programs",
        "author": "Harold Abelson, Gerald Jay Sussman",
        "publisher": "MIT Press",
        "published_date": "1985-07-25",
        "page_count": 657,
        "language": "English",
    },
    {
        "id": 7,
        "title": "Artificial Intelligence: A Modern Approach",
        "author": "Stuart Russell, Peter Norvig",
        "publisher": "Pearson",
        "published_date": "1995-12-11",
        "page_count": 1152,
        "language": "English",
    },
    {
        "id": 8,
        "title": "Computer Networking: A Top-Down Approach",
        "author": "James F. Kurose, Keith W. Ross",
        "publisher": "Pearson",
        "published_date": "2000-06-01",
        "page_count": 888,
        "language": "English",
    },
    {
        "id": 9,
        "title": "Deep Learning",
        "author": "Ian Goodfellow, Yoshua Bengio, Aaron Courville",
        "publisher": "MIT Press",
        "published_date": "2016-11-18",
        "page_count": 800,
        "language": "English",
    },
    {
        "id": 10,
        "title": "Operating System Concepts",
        "author": "Abraham Silberschatz, Peter B. Galvin, Greg Gagne",
        "publisher": "Wiley",
        "published_date": "1983-05-03",
        "page_count": 976,
        "language": "English",
    },
]
