"""fixing-book-model-almost-done-but-time-stamp-still-remains

Revision ID: 1d7730bf8086
Revises: 4fc3d3c9e89d
Create Date: 2025-03-12 17:20:00.599906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1d7730bf8086'
down_revision: Union[str, None] = '4fc3d3c9e89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
