"""add-role-field

Revision ID: df1b5e9f5f7b
Revises: e4d1acc019e2
Create Date: 2025-03-12 16:16:45.876606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'df1b5e9f5f7b'
down_revision: Union[str, None] = 'e4d1acc019e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'book', 'user', ['user_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'user_uid')
    # ### end Alembic commands ###
